# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "groupers"
client_id = "13906b00d187032833fe9eba361ab122"
application_url = "https://jon-efficient-okay-astronomy.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://jon-efficient-okay-astronomy.trycloudflare.com/auth/callback",
  "https://jon-efficient-okay-astronomy.trycloudflare.com/auth/shopify/callback",
  "https://jon-efficient-okay-astronomy.trycloudflare.com/api/auth/callback",
  "https://jon-efficient-okay-astronomy.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "tools-iot.myshopify.com"
